name: deploy smartAI to VPS

on:
    push:
        branches:
            - development
jobs:
    build-and-deploys:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm install

            - name: Build smartAI
              env:
                  VITE_API_BASE_URL: ${{secrets.VITE_API_BASE_URL}}
              run: npm run build

            - name: Remove Old File on VPS
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{secrets.VPS_HOST}}
                  username: ${{secrets.VPS_USER}}
                  key: ${{secrets.VPS_KEY}}
                  script: |
                     sudo find /var/www/smartai -mindepth 1 -delete

            - name: upload new build to VPS
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{secrets.VPS_HOST}}
                  username: ${{ secrets.VPS_USER }}
                  key: ${{ secrets.VPS_KEY }}
                  source: "dist/**"
                  strip_components: 1
                  target: "/var/www/smartai"

            - name: restart Nginx
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{secrets.VPS_HOST}}
                  username: ${{ secrets.VPS_USER }}
                  key: ${{ secrets.VPS_KEY }}
                  script: |
                      sudo systemctl restart nginx

